
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?characterEncoding=UTF-8
    username: root
    password: 123456
